### ISSUE TITLE
Ruby on Rails group project set-up 

### ISSUE THREAD

**Issue by AbdusSattar-70** [peterdtitan/food-recipe-app#12]
### Below is the link to the Kanban Board for this project:

[Food Recipe App: Kanban Board](https://github.com/users/peterdtitan/projects/7)

This is a 2-person project and the authors are:
@peterdtitan
@AbdusSattar-70

**Comment by zainsadaqat** [comment]
# Pull Request Approved ✅ 🎊 🎉 
## Hello @AbdusSattar-70 and @peterdtitan  👋 

## Things to appreciate
- [ ] Tasks are distributed equally among all 👍 

### Your project is complete!  There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 

<img src="https://media1.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
